### ISSUE TITLE
Example files for each sub-reader

### ISSUE THREAD

**Issue by lukaspie** [FAIRmat-NFDI/pynxtools-xps#15]
Currently, only the SLE reader has an example file.
We need examples for:

- SPECS GmbH
  - [x] .sle: [SpecsLabProdigy](https://www.specs-group.com/nc/specs/products/detail/prodigy/) files, propietary format of SPECS GmbH
  - [x] .xml: SpecsLab 2files, XML format from SPECS GmbH, software version v.1.6 -> #16 
  - [x]  .xy: SpecsLabProdigy export format in XY format
- [Phi MultiPak](https://www.phi.com/surface-analysis-equipment/genesis.html#software:multi-pak-data-reduction-software/) files, propietary format of PHI Electronics, software version SS 3.3.3.2)
   - [x] .spe data (regular spectra) and
   - [x] .pro data (sputter depth profiling)
 - VAMAS files, ISO standard data transfer format (ISO 14976)
   - [x]  REGULAR format
   - [x]  IRREGULAR format -> need to have subparser first -> https://github.com/FAIRmat-NFDI/pynxtools-xps/issues/9
   - [x] TXT file exported by [CasaXPS](https://www.casaxps.com/) analysis software
   - [x] ~~Data analysis in CasaXPS stored in .vms~~ (will be its own PR, see #21 )
- [Scienta Omicron](https://scientaomicron.com/en)
  - [x] .txt exported by Scienta instruments
  - [x] ~~IGOR format of Scienta~~ (will be its own PR, see #28)
